version: '3.4'

x-app: &app
  build:
    context: .
    dockerfile: Dockerfile
    args:
      RUBY_VERSION: '2.6.3'
      PG_MAJOR: '11'
      BUNDLER_VERSION: '2.0.2'
      NODE_MAJOR: '11'
  environment: &env
    RAILS_ENV: ${RAILS_ENV:-development}
  image: rails-chat-tutorial:1.0.0
  container_name: chat_app
  tmpfs:
    - /tmp

x-backend: &backend
  <<: *app
  stdin_open: true
  tty: true
  container_name: chat_backend
  volumes:
    - ../../rails-chat-tutorial:/app
    - chat_rails_cache:/app/tmp/cache
    - chat_bundle:/bundle
  environment:
    <<: *env
    REDIS_URL: redis://redis:6379/
    # DATABASE_URL: postgres//saifi:saifi@postgres:5432
    BOOTSNAP_CACHE_DIR: /bundle/bootsnap
    EDITOR: vi
  depends_on:
    - postgres
    - redis

services:
  it:
    <<: *backend
    command: /bin/bash
    container_name: chat_it
    ports:
      - '3000:3000'

  rails:
    <<: *backend
    command: >
      bash -c "bundle install
      && bundle exec rails server -b 0.0.0.0"
    container_name: chat_rails
    ports:
      - '3000:3000'

  redis:
    image: redis:3.2-alpine
    container_name: chat_redis
    volumes:
      - chat_redis:/data
    ports:
      - 6379

  postgres:
    image: postgres:11.1
    container_name: chat_postgres
    volumes:
      - chat_postgres:/var/lib/postgresql/data
      - ./log:/root/log:cached
    env_file:  db.env
    ports:
      - 5432

volumes:
  chat_postgres:
  chat_redis:
  chat_bundle:
  chat_rails_cache:
